name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish Project
      run: |
        dotnet restore
        dotnet publish VRChatAutoFishing/VRChatAutoFishing.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=false -o ./publish-output

    - name: Create Release and Upload Asset
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        
        gh release create "v$VERSION" \
          --title "v$VERSION" \
          --notes "Automatic release for version $VERSION" \
          ./publish-output/VRChatAutoFishing.exe
